import { MagnifyingGlassIcon } from "@heroicons/react/24/outline";
import CustomButton from "../components/CustomButton";
import CustomInput from "../components/CustomInput";

const Home = () => {
  const communityImages = [
    {
      imgId: 1,
      username: "Aniket More",
      prompt: "create a bicycle",
      imgUrl: "https://picsum.photos/id/237/200/300",
    },
    {
      imgId: 2,
      username: "Aniket More",
      prompt: "create a bicycle",
      imgUrl: "https://picsum.photos/id/237/200/300",
    },
    {
      imgId: 3,
      username: "Aniket More",
      prompt: "create a bicycle",
      imgUrl: "https://picsum.photos/id/237/200/300",
    },
    {
      imgId: 4,
      username: "Aniket More",
      prompt: "create a bicycle",
      imgUrl: "https://picsum.photos/id/237/200/300",
    },
    {
      imgId: 5,
      username: "Aniket More",
      prompt: "create a bicycle",
      imgUrl: "https://picsum.photos/id/237/200/300",
    },
    {
      imgId: 6,
      username: "Aniket More",
      prompt: "create a bicycle",
      imgUrl: "https://picsum.photos/id/237/200/300",
    },
    {
      imgId: 7,
      username: "Aniket More",
      prompt: "create a bicycle",
      imgUrl: "https://picsum.photos/id/237/200/300",
    },
    {
      imgId: 8,
      username: "Aniket More",
      prompt: "create a bicycle",
      imgUrl: "https://picsum.photos/id/237/200/300",
    },
    {
      imgId: 9,
      username: "Aniket More",
      prompt: "create a bicycle",
      imgUrl: "https://picsum.photos/id/237/200/300",
    },
    {
      imgId: 10,
      username: "Aniket More",
      prompt: "create a bicycle",
      imgUrl: "https://picsum.photos/id/237/200/300",
    },
  ];

  return (
    <div className="flex flex-col h-screen">
      <section className="home px-6 py-3 md:px-12 lg:px-20 flex-1 overflow-y-auto">
        <div className="home-text">
          <h2 className="text-5xl font-extrabold mt-6 mb-3">
            Community Showcase
          </h2>
          <span className="text-xl text-gray-600">
            See images generated by our AI. Be inspired and see what others have
            created.
          </span>
        </div>

        <div className="mt-8">
          <CustomInput
            className=""
            placeholder="Search images"
            isIcon={true}
            iconImage={<MagnifyingGlassIcon />}
            onChange={() => {}}
          ></CustomInput>
        </div>

        <div className="image-grid mt-6 md:mt-10 grid grid-cols-2 auto-rows-[10rem] md:grid-cols-3 md:auto-rows-[12rem] lg:grid-cols-4 lg:auto-rows-[15rem] gap-3">
          {communityImages.map((image: any) => (
            <div
              key={image.imgId}
              className="relative group first:col-span-2 first:row-span-2 row-span-1 max-width-100 border-2 rounded-md overflow-hidden flex justify-center"
            >
              <img
                src={image.imgUrl}
                className="w-full h-full object-cover"
                alt=""
              />

              <div className="absolute hidden group-hover:block border-2 bottom-0 w-full p-2 text-center bg-gray-400">
                <span className="font-semibold">{image.username}</span> <br />
                <span className="truncate">{image.prompt}</span>
              </div>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
};

export default Home;
