export const surpriseMePrompts = [
  "a cute smiling cat",
  "sunset over desert dunes",
  "floating hot air balloon",
  "golden retriever puppy",
  "ice cream cone swirl",
  "tropical beach palm trees",
  "cozy mountain cabin",
  "vintage red bicycle",
  "colorful city skyline",
  "sleeping baby panda",
  "cup of steaming coffee",
  "snowy pine forest",
  "field of daisies",
  "moonlit night sky",
  "bright sunflower closeup",
  "leaping dolphin splash",
  "autumn leaves falling",
  "rainy window view",
  "blooming cherry blossoms",
  "roaring campfire glow",
  "ancient stone ruins",
  "paper boat on river",
  "whimsical fairy door",
  "rustic wooden bridge",
  "ballerina in studio",
  "butterfly on flower",
  "starfish on shore",
  "colorful paint splatter",
  "space shuttle launch",
  "crystal clear waterfall",
  "lanterns in night sky",
  "windmill in tulip field",
  "skateboard at sunset",
  "owl in moonlight",
  "basket of fresh fruit",
  "goldfish in bowl",
  "corgi wearing sunglasses",
  "geometric pattern art",
  "rainbow over hills",
  "vintage typewriter keys",
  "cheese pizza slice",
  "koi fish pond",
  "hot chocolate mug",
  "surfboard on sand",
  "sushi platter art",
  "glowing lantern festival",
  "abstract neon shapes",
  "horse galloping field",
  "palm leaf shadow",
  "marble chess pieces",
  "sailboat on lake",
  "jazz saxophone player",
  "ancient leather book",
  "cupcake with sprinkles",
  "origami crane closeup",
  "cup of herbal tea",
  "candlelit dinner table",
  "rainforest waterfall",
  "vintage camera lens",
  "rusty key in lock",
  "lighthouse by sea",
  "colorful hot air balloons",
  "kitten and yarn ball",
  "freshly baked bread",
  "stacked pebbles on beach",
  "moon reflected in lake",
  "sunflower field path",
  "tea set on tray",
  "birch tree forest",
  "glowing bioluminescent waves",
  "comic book explosion",
  "paper airplane flight",
  "ice crystals on window",
  "foggy morning bridge",
  "lantern on wooden dock",
  "bamboo forest trail",
  "red fox in snow",
  "golden sunset over city",
  "vintage vinyl record",
  "camping tent under stars",
  "rustic barn door",
  "iceberg in blue sea",
  "crow on bare branch",
  "flower crown portrait",
  "stack of colorful books",
  "roller coaster at night",
  "city park bench",
  "butterfly wings closeup",
  "peony flower bloom",
  "desert cactus sunset",
  "knitting yarn ball",
  "classic car at drive‑in",
  "splashing red paint",
  "glass of lemonade",
  "forest path in fog",
  "festival fireworks sky",
  "stained glass window",
  "golden crown on velvet",
  "secret garden gate",
];
